#!/usr/bin/env bash
#
# Build the patched tree with the real Xcode toolchain.
#
# This is deliberately not a Nix derivation. The project is an .xcodeproj that
# links SkyLight.framework out of /System/Library/PrivateFrameworks, embeds
# three local SwiftPM packages, and runs a code-signing phase against the login
# keychain. None of that survives the Nix sandbox, and nixpkgs' xcbuild does not
# reimplement enough of xcodebuild to take its place. The Nix side of this repo
# packages *this script* and pins *what* it builds; the build itself is impure
# by necessity, and pretending otherwise would only hide it.

. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

require_xcode
"$ATU_ROOT/scripts/fetch.sh"

VERSION="$(pin version)"
IDENTITY="$("$ATU_ROOT/scripts/signing-identity.sh" --resolve)"
DEPLOYMENT_TARGET="${ATU_DEPLOYMENT_TARGET:-12.0}"

bold "Building AltTab ${VERSION}"
info "Xcode:    $("$XCODEBUILD" -version | head -1) at $DEVELOPER_DIR"
info "identity: ${IDENTITY}"
info "min macOS: ${DEPLOYMENT_TARGET} (upstream ships 10.14.4; see config/local.xcconfig)"

# Upstream's release config is a notarized Developer ID build signed with a
# certificate we do not have, so every value below is an override. release.xcconfig
# ends with `#include? "local.xcconfig"`, so this file wins over everything it sets.
cat > "$SRC/config/local.xcconfig" <<XCCONFIG
// Generated by alt-tab-unlocked. Do not edit; fetch.sh rewrites the tree.

// Upstream's CI writes this from semantic-release. Info.plist substitutes it
// into both CFBundleShortVersionString and CFBundleVersion, so without it the
// app reports a literal \$(CURRENT_PROJECT_VERSION).
CURRENT_PROJECT_VERSION = ${VERSION}

// Empty on purpose. AppCenter crash reporting stays compiled in, but it starts
// with networkRequestsAllowed = false and only ever flips that after an explicit
// "send this crash report" click, which cannot reach anywhere without a secret.
APPCENTER_SECRET =

CODE_SIGN_IDENTITY = ${IDENTITY}
CODE_SIGN_STYLE = Manual
DEVELOPMENT_TEAM =
PROVISIONING_PROFILE_SPECIFIER =

// --timestamp would call Apple's timestamp authority for a signature nobody is
// going to notarize. --deep stays: Sparkle embeds XPC services that need valid
// signatures for the updater to load at all.
OTHER_CODE_SIGN_FLAGS = --timestamp=none --deep --options runtime

// Upstream treats warnings as errors, which is right for a project that pins its
// own CI toolchain. Here the toolchain is whatever Xcode the Mac happens to have,
// so a new SDK deprecating one API would turn into a build failure that has
// nothing to do with the patches.
SWIFT_TREAT_WARNINGS_AS_ERRORS = NO

// Upstream ships 10.14.4 because it distributes to everyone. Each new SDK raises
// the floor it will accept, and Xcode 27 rejects 10.14.4 outright, so inheriting
// upstream's value makes the build fail on a toolchain upgrade for a reason that
// has nothing to do with this machine.
//
// The cost of raising it is that this build will not run on anything older than
// the value below — which is fine for an app built on the Mac that runs it, and
// is the whole point of building it here. Override with ATU_DEPLOYMENT_TARGET if
// you ever want to hand the result to an older Mac.
MACOSX_DEPLOYMENT_TARGET = ${DEPLOYMENT_TARGET}
XCCONFIG
ok "wrote config/local.xcconfig"

rm -rf "$SRC/DerivedData"
LOG="$CACHE/build.log"
if ! "$XCODEBUILD" \
      -project "$SRC/alt-tab-macos.xcodeproj" \
      -scheme Release \
      -configuration Release \
      -derivedDataPath "$SRC/DerivedData" \
      -quiet \
      build > "$LOG" 2>&1; then
  tail -60 "$LOG" >&2
  die "xcodebuild failed. Full log: $LOG"
fi

BUILT="$SRC/DerivedData/Build/Products/Release/AltTab.app"
[ -d "$BUILT" ] || die "build reported success but $BUILT is missing. Log: $LOG"

/usr/bin/codesign --verify --deep --strict "$BUILT" 2>/dev/null \
  || warn "codesign --verify is unhappy; the app will still run but Gatekeeper may complain"

ok "built $BUILT"
printf '%s\n' "$BUILT" > "$CACHE/last-build-path"
